Work in progress: SMS service
sunrisemovement/hubhub pull request #14
Opened 2020-11-13 20:28 UTC by asross

This is a work-in-progress feature to add an endpoint to support text messaging-based search using [Twilio's Ruby API](https://www.twilio.com/docs/sms/quickstart/ruby).

Here's an example conversation:
![IMG_0581](https://user-images.githubusercontent.com/1022564/99117925-96473980-25c4-11eb-867e-c4b417ddade0.jpg)
![IMG_0582](https://user-images.githubusercontent.com/1022564/99117927-9810fd00-25c4-11eb-8369-f4c8afbbfb3f.jpg)

2020-11-13 20:28 UTC, asross commented on airtable.rb
> +  end
These methods are a bit presentational, and might be better extracted to some kind of SMS template helper object.

2020-11-13 20:30 UTC, asross commented on sms_service.rb
> +    end
I've felt for a while that it's a bit wasteful for us to always make API calls to Hubhub to get every single hub whenever we make any requests, so I cached it in a class variable (that refreshes every time the server restarts). Ideally, though, we should either (1) _not_ do this, or (2) invalidate the cache every few min.

2020-12-21 23:14 UTC, BrianHicks requested changes
sorry, don't have time to review all of this right now but let me know as it gets closer to approval and I'll give it another go-over!

2020-12-21 23:14 UTC, BrianHicks commented on airtable.rb
> +    if @cached_hubs.nil? || @cached_at.nil? || Time.now - @cached_at > timeout
this feels like a helper method waiting to happen!

2020-12-21 23:14 UTC, BrianHicks commented on airtable.rb
> +  def self.cached_visible(timeout=10*60)
the names of these methods are more about implementation details than they are intent. Should this just be like `def self.visible(maximum_staleness=10*60)` maybe? Similar for `self.cached_editable`.

2020-12-21 23:14 UTC, BrianHicks commented on sms_service.rb
> +  d = 6371 * c * (miles ? 1 / 1.60934 : 1)
this assigns as the final statement. Is that necessary here? There's no place for `d` to be used.

2020-12-21 23:14 UTC, BrianHicks commented on sms_service.rb
> +      "information right now 😞 Try searching for a different hub!"
if there are the mentioned data issues, should we ask the person we're texting to raise that somewhere, or automatically report it?

2020-12-22 01:43 UTC, asross commented on airtable.rb
> +  def self.cached_visible(timeout=10*60)
Agreed -- that makes more sense!

2020-12-22 01:45 UTC, asross commented on airtable.rb
> +    if @cached_hubs.nil? || @cached_at.nil? || Time.now - @cached_at > timeout
Agreed as well, though I'm not 100% sure of the best way to extract it. Maybe this is a job for some kind of service object / library, though it might also make sense to wait until we have another use-case.

2020-12-22 01:46 UTC, asross commented on sms_service.rb
> +  d = 6371 * c * (miles ? 1 / 1.60934 : 1)
Yep, you're right, we don't need that. I will confess that I copy-pasted this, so the variable name styles probably clash a bit with the rest of the app...

2020-12-22 01:47 UTC, asross commented on sms_service.rb
> +      "information right now 😞 Try searching for a different hub!"
Hmm, good point. I don't think it makes sense for the person we're texting to report it since they're new to Sunrise, but I'll look into sending a Honeybadger notification or at least making some kind of greppable log statement.

2020-12-22 14:23 UTC, asross commented on sms_service.rb
> +      "information right now 😞 Try searching for a different hub!"
So, it turns out that invoking Honeybadger from here is a little bit trickier than I thought, and I actually think the better fix for this problem is to ensure `Hub.visible` doesn't return hubs without contact information. I'm wondering if for expediency's sake, we can defer that change to another PR!

2020-12-22 14:32 UTC, asross commented on sms_service.rb
> +        JSON.parse(request.env['rack.input'].read) rescue {}
Just by way of explanation, for some reason, Strive staging JSON POST parameters aren't ending up in the `params` variable despite them sending the `Content-Type: application/json` header. This manually parses the JSON in case that problem persists in production.

2020-12-22 14:44 UTC, BrianHicks approved these changes
some little tweaky suggestions to the language, but overall lookin' good!

2020-12-22 14:44 UTC, BrianHicks commented on sms_service.rb
> +  end
"on Twitter at https://twitter.com/StlSunrise" is like… obvious? I can tell from the link that that's a Twitter account. Do we have some that are just `@StlSunrise` or whatever?

2020-12-22 14:44 UTC, BrianHicks commented on sms_service.rb
> +    end
I'm on the side of (1) above. Would it be possible to get only the hub we care about? OTOH application-level caching on the server could be intelligent and save clients the trouble.

2020-12-22 14:44 UTC, BrianHicks commented on sms_service.rb
> +    @hubs ||= begin
I did not know you could use a `begin` without a `rescue`. Neat trick!

2020-12-22 14:44 UTC, BrianHicks commented on sms_service.rb
> +      Sorry, we couldn't find any active Sunrise hubs #{in_location} 😞
BTW I really like the names of these methods (e.g. `in_location`) in the interpolations here. Really readable.

2020-12-22 14:44 UTC, BrianHicks commented on sms_service.rb
> +      If #{hub.name} is far away, you can also consider starting your own hub: #{START_HUB_URL}
language tweak: "too far away"? For example, if I lived in Wyoming I might be more OK driving 20 miles to something than if I lived in Boston/Cambridge.

2020-12-22 14:44 UTC, BrianHicks commented on sms_service.rb
> +        JSON.parse(request.env['rack.input'].read) rescue {}
Pokémon exception! Maybe move this to something like:

```ruby
def search_params
  # current method body
rescue WhateverJsonParsingError
  {}
end
```

2020-12-22 14:44 UTC, BrianHicks commented on test/sms_test.rb
> +      'State' => 'NJ',
😆

2020-12-22 14:44 UTC, BrianHicks commented on sms_service.rb
> +        JSON.parse(request.env['rack.input'].read) rescue {}
computers! How do they work!?

2020-12-22 14:50 UTC, asross commented on sms_service.rb
> +      If #{hub.name} is far away, you can also consider starting your own hub: #{START_HUB_URL}
Yeah, that's better :)

2020-12-22 15:03 UTC, asross commented on sms_service.rb
> +      Sorry, we couldn't find any active Sunrise hubs #{in_location} 😞
Thanks :)

2020-12-22 15:05 UTC, asross commented on sms_service.rb
> +  end
Ahh, that's a good point -- it's always going to be the full URL, so we can drop the platform names.

2020-12-22 15:36 UTC, merged